name: Compile Check

on:
  push:
    paths:
      - 'src/**'
      - 'examples/**'
  pull_request:
    paths:
      - 'src/**'
      - 'examples/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        board: [ "arduino:avr:uno", "esp8266:esp8266:nodemcuv2", "esp32:esp32:esp32" ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Install Platforms
        run: |
          arduino-cli core update-index
          if [ "${{ matrix.board }}" == "esp8266:esp8266:nodemcuv2" ]; then
            arduino-cli core update-index --additional-urls http://arduino.esp8266.com/stable/package_esp8266com_index.json
            arduino-cli core install esp8266:esp8266 --additional-urls http://arduino.esp8266.com/stable/package_esp8266com_index.json
          elif [ "${{ matrix.board }}" == "esp32:esp32:esp32" ]; then
            arduino-cli core update-index --additional-urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
            arduino-cli core install esp32:esp32 --additional-urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
          else
            arduino-cli core install arduino:avr
          fi

      - name: Compile Examples
        run: |
          for example in examples/*/*.ino; do
            echo "Compiling $example for ${{ matrix.board }}..."
            arduino-cli compile --fqbn ${{ matrix.board }} $example --library .
          done
